#ifndef MFCC_MULTICLASS_MODEL_DATA_H
#define MFCC_MULTICLASS_MODEL_DATA_H

#include <stddef.h>

#define MFCC_MULTICLASS_WINDOW_SAMPLES 16000
#define MFCC_MULTICLASS_FRAME_LENGTH 480
#define MFCC_MULTICLASS_FRAME_STEP 320
#define MFCC_MULTICLASS_FFT_LENGTH 512
#define MFCC_MULTICLASS_SPECTROGRAM_BINS 257
#define MFCC_MULTICLASS_MEL_BINS 40
#define MFCC_MULTICLASS_MFCC_COUNT 13
#define MFCC_MULTICLASS_FEATURE_FRAMES 49
#define MFCC_MULTICLASS_FEATURE_CHANNELS 39
#define MFCC_MULTICLASS_FEATURE_DIM 1911
#define MFCC_MULTICLASS_CLASS_COUNT 6
#define MFCC_MULTICLASS_HEALTHY_INDEX 0

extern const float g_mfcc_multiclass_weight[MFCC_MULTICLASS_CLASS_COUNT * MFCC_MULTICLASS_FEATURE_DIM];
extern const float g_mfcc_multiclass_bias[MFCC_MULTICLASS_CLASS_COUNT];
extern const float g_mfcc_multiclass_mel_matrix[MFCC_MULTICLASS_SPECTROGRAM_BINS * MFCC_MULTICLASS_MEL_BINS];
extern const float g_mfcc_multiclass_dct_matrix[MFCC_MULTICLASS_MEL_BINS * MFCC_MULTICLASS_MFCC_COUNT];
extern const char *const g_mfcc_multiclass_class_names[MFCC_MULTICLASS_CLASS_COUNT];
extern const char *const g_mfcc_multiclass_display_names[MFCC_MULTICLASS_CLASS_COUNT];

#endif // MFCC_MULTICLASS_MODEL_DATA_H
